// Generated from Rust service definitions. Do not edit.
import { RpcClient, type Method } from '@gcoms/rpc';
import * as guards from './rpc-validators.js';
// Generated by cargo run -p gchat-api --bin gchat-types. Do not edit.
export const API_VERSION = 2;
export const MAX_INPUT_BYTES = 12000;
export type InstanceInfo = { id: string, label: string, bootId: string, locked: boolean, protocolLocked: boolean, profileExists: boolean, archiveExists: boolean, safetyNumber: string, capabilities: Array<string>, };
export type Member = { id: string, nickname: string, isSelf: boolean, capabilities: Array<string>, };
export type Conversation = { provider: string | null, id: string, channelId: string, kind: ConversationKind, name: string, topic: string, active: boolean, owner: boolean, members: Array<Member>, unread: number, lastMessageId: string | null, inputLimitBytes: number, commands: Array<CommandSpec>, };
export type ConversationKind = "channel" | "query" | "archive";
export type Message = { id: string, conversationId: string, memberId: string | null, nickname: string, body: string, timestamp: number, mine: boolean,
/**
 * Local archive acceptance is the only fact currently available for outgoing text.
 */
delivery: Delivery | null, result: ActionResult | null, };
export type ActionResult = { id: string, messageId: string | null, state: string,
/**
 * Exact signed bytes, base64 encoded; views decode only for display.
 */
outputBase64: string | null, stderr: boolean, details: Array<string>, artifacts: Array<Artifact>, };
export type Artifact = { name: string, url: string, };
export type Delivery = "local_accepted";
export type CommandSpec = { name: string, usage: string, description: string, scope: string, capability: string | null, available: boolean, };
export type DirectoryEntry = { name: string, joined: boolean, conversation: string | null, };
export type CommandOutput = { "kind": "help", commands: Array<CommandSpec>, } | { "kind": "directory", channels: Array<DirectoryEntry>, } | { "kind": "invitation", channel: string, link: string, expires: number, localOnly: boolean, } | { "kind": "text", title: string, text: string, } | { "kind": "status", text: string, } | { "kind": "close", conversation: string, };
export type InputHistoryEntry = { conversation: string | null, text: string, };
export type ProviderStatus = { id: string, code: string, message: string, retryable: boolean, };
export type Snapshot = { instance: InstanceInfo, revision: string, conversations: Array<Conversation>, commandHistory: Array<string>, inputHistory: Array<InputHistoryEntry>, providerErrors: Array<ProviderStatus>, };
export type HistoryPage = { messages: Array<Message>, before: string | null, };
export type Completion = { text: string, description: string, };
export type Request = { "kind": "identify" } | { "kind": "unlock", passphrase: string, create: boolean, } | { "kind": "lock" } | { "kind": "disconnect" } | { "kind": "snapshot" } | { "kind": "catalogue", conversation: string | null, } | { "kind": "history", conversation: string, before: string | null, limit: number, } | { "kind": "search", conversation: string, text: string, before: string | null, limit: number, } | { "kind": "submit", operation_id: string, conversation: string | null, text: string, } | { "kind": "complete", conversation: string | null, text: string, } | { "kind": "mark_read", conversation: string, message_id: string, } | { "kind": "events", after: string, wait_ms: number, };
export type Response = { "kind": "instance", instance: InstanceInfo, } | { "kind": "snapshot", snapshot: Snapshot, } | { "kind": "history", page: HistoryPage, } | { "kind": "completed", items: Array<Completion>, } | { "kind": "catalogue", commands: Array<CommandSpec>, } | { "kind": "projection", conversations: Array<Conversation>, revision: string, } | { "kind": "output", conversation: string | null, output: CommandOutput, } | { "kind": "applied", conversation: string | null, notice: string | null, } | { "kind": "changed", revision: string, } | { "kind": "error", code: string, message: string, };
export type RequestEnvelope = { version: number, instance_id: string | null, request: Request, };
export type ResponseEnvelope = { version: number, instance_id: string, response: Response, };

export type ChatError = { code: string, message: string, };
export type Applied = { conversation: string | null, notice: string | null, };
export type SubmitOutcome = { "kind": "applied", conversation: string | null, notice: string | null, } | { "kind": "output", conversation: string | null, output: CommandOutput, };

export const SERVICE = "ghost.chat";
export const SERVICE_VERSION = 1;
export const methods = {
"identify": { id: "identify", kind: "query", args: (value: unknown): value is Record<string, never> => guards.identify_args(value), output: (value: unknown): value is { id: string, label: string, bootId: string, locked: boolean, protocolLocked: boolean, profileExists: boolean, archiveExists: boolean, safetyNumber: string, capabilities: Array<string>, } => guards.identify_output(value), error: (value: unknown): value is { code: string, message: string, } => guards.identify_error(value) } satisfies Method<Record<string, never>, { id: string, label: string, bootId: string, locked: boolean, protocolLocked: boolean, profileExists: boolean, archiveExists: boolean, safetyNumber: string, capabilities: Array<string>, }, { code: string, message: string, }>,
"unlock": { id: "unlock", kind: "session", args: (value: unknown): value is { passphrase: string, create: boolean, } => guards.unlock_args(value), output: (value: unknown): value is { instance: InstanceInfo, revision: string, conversations: Array<Conversation>, commandHistory: Array<string>, inputHistory: Array<InputHistoryEntry>, providerErrors: Array<ProviderStatus>, } => guards.unlock_output(value), error: (value: unknown): value is { code: string, message: string, } => guards.unlock_error(value) } satisfies Method<{ passphrase: string, create: boolean, }, { instance: InstanceInfo, revision: string, conversations: Array<Conversation>, commandHistory: Array<string>, inputHistory: Array<InputHistoryEntry>, providerErrors: Array<ProviderStatus>, }, { code: string, message: string, }>,
"lock": { id: "lock", kind: "session", args: (value: unknown): value is Record<string, never> => guards.lock_args(value), output: (value: unknown): value is { id: string, label: string, bootId: string, locked: boolean, protocolLocked: boolean, profileExists: boolean, archiveExists: boolean, safetyNumber: string, capabilities: Array<string>, } => guards.lock_output(value), error: (value: unknown): value is { code: string, message: string, } => guards.lock_error(value) } satisfies Method<Record<string, never>, { id: string, label: string, bootId: string, locked: boolean, protocolLocked: boolean, profileExists: boolean, archiveExists: boolean, safetyNumber: string, capabilities: Array<string>, }, { code: string, message: string, }>,
"disconnect": { id: "disconnect", kind: "session", args: (value: unknown): value is Record<string, never> => guards.disconnect_args(value), output: (value: unknown): value is { instance: InstanceInfo, revision: string, conversations: Array<Conversation>, commandHistory: Array<string>, inputHistory: Array<InputHistoryEntry>, providerErrors: Array<ProviderStatus>, } => guards.disconnect_output(value), error: (value: unknown): value is { code: string, message: string, } => guards.disconnect_error(value) } satisfies Method<Record<string, never>, { instance: InstanceInfo, revision: string, conversations: Array<Conversation>, commandHistory: Array<string>, inputHistory: Array<InputHistoryEntry>, providerErrors: Array<ProviderStatus>, }, { code: string, message: string, }>,
"snapshot": { id: "snapshot", kind: "query", args: (value: unknown): value is Record<string, never> => guards.snapshot_args(value), output: (value: unknown): value is { instance: InstanceInfo, revision: string, conversations: Array<Conversation>, commandHistory: Array<string>, inputHistory: Array<InputHistoryEntry>, providerErrors: Array<ProviderStatus>, } => guards.snapshot_output(value), error: (value: unknown): value is { code: string, message: string, } => guards.snapshot_error(value) } satisfies Method<Record<string, never>, { instance: InstanceInfo, revision: string, conversations: Array<Conversation>, commandHistory: Array<string>, inputHistory: Array<InputHistoryEntry>, providerErrors: Array<ProviderStatus>, }, { code: string, message: string, }>,
"catalogue": { id: "catalogue", kind: "query", args: (value: unknown): value is { conversation: string | null, } => guards.catalogue_args(value), output: (value: unknown): value is Array<{ name: string, usage: string, description: string, scope: string, capability: string | null, available: boolean, }> => guards.catalogue_output(value), error: (value: unknown): value is { code: string, message: string, } => guards.catalogue_error(value) } satisfies Method<{ conversation: string | null, }, Array<{ name: string, usage: string, description: string, scope: string, capability: string | null, available: boolean, }>, { code: string, message: string, }>,
"history": { id: "history", kind: "query", args: (value: unknown): value is { conversation: string, before: string | null, limit: number, } => guards.history_args(value), output: (value: unknown): value is { messages: Array<Message>, before: string | null, } => guards.history_output(value), error: (value: unknown): value is { code: string, message: string, } => guards.history_error(value) } satisfies Method<{ conversation: string, before: string | null, limit: number, }, { messages: Array<Message>, before: string | null, }, { code: string, message: string, }>,
"search": { id: "search", kind: "query", args: (value: unknown): value is { conversation: string, text: string, before: string | null, limit: number, } => guards.search_args(value), output: (value: unknown): value is { messages: Array<Message>, before: string | null, } => guards.search_output(value), error: (value: unknown): value is { code: string, message: string, } => guards.search_error(value) } satisfies Method<{ conversation: string, text: string, before: string | null, limit: number, }, { messages: Array<Message>, before: string | null, }, { code: string, message: string, }>,
"submit": { id: "submit", kind: "operation", args: (value: unknown): value is { conversation: string | null, text: string, } => guards.submit_args(value), output: (value: unknown): value is { "kind": "applied", conversation: string | null, notice: string | null, } | { "kind": "output", conversation: string | null, output: CommandOutput, } => guards.submit_output(value), error: (value: unknown): value is { code: string, message: string, } => guards.submit_error(value) } satisfies Method<{ conversation: string | null, text: string, }, { "kind": "applied", conversation: string | null, notice: string | null, } | { "kind": "output", conversation: string | null, output: CommandOutput, }, { code: string, message: string, }>,
"complete": { id: "complete", kind: "query", args: (value: unknown): value is { conversation: string | null, text: string, } => guards.complete_args(value), output: (value: unknown): value is Array<{ text: string, description: string, }> => guards.complete_output(value), error: (value: unknown): value is { code: string, message: string, } => guards.complete_error(value) } satisfies Method<{ conversation: string | null, text: string, }, Array<{ text: string, description: string, }>, { code: string, message: string, }>,
"mark_read": { id: "mark_read", kind: "operation", args: (value: unknown): value is { conversation: string, message_id: string, } => guards.mark_read_args(value), output: (value: unknown): value is { conversation: string | null, notice: string | null, } => guards.mark_read_output(value), error: (value: unknown): value is { code: string, message: string, } => guards.mark_read_error(value) } satisfies Method<{ conversation: string, message_id: string, }, { conversation: string | null, notice: string | null, }, { code: string, message: string, }>,
"events": { id: "events", kind: "query", args: (value: unknown): value is { after: string, wait_ms: number, } => guards.events_args(value), output: (value: unknown): value is string => guards.events_output(value), error: (value: unknown): value is { code: string, message: string, } => guards.events_error(value) } satisfies Method<{ after: string, wait_ms: number, }, string, { code: string, message: string, }>
};
export function createChatClient(rpc: RpcClient) { return {
"identify": (args: Record<string, never>) => rpc.call(methods.identify, args),
"unlock": (args: { passphrase: string, create: boolean, }) => rpc.call(methods.unlock, args),
"lock": (args: Record<string, never>) => rpc.call(methods.lock, args),
"disconnect": (args: Record<string, never>) => rpc.call(methods.disconnect, args),
"snapshot": (args: Record<string, never>) => rpc.call(methods.snapshot, args),
"catalogue": (args: { conversation: string | null, }) => rpc.call(methods.catalogue, args),
"history": (args: { conversation: string, before: string | null, limit: number, }) => rpc.call(methods.history, args),
"search": (args: { conversation: string, text: string, before: string | null, limit: number, }) => rpc.call(methods.search, args),
"submit": (args: { conversation: string | null, text: string, }) => rpc.call(methods.submit, args),
"prepare_submit": (args: { conversation: string | null, text: string, }) => rpc.prepare(methods.submit, args),
"complete": (args: { conversation: string | null, text: string, }) => rpc.call(methods.complete, args),
"mark_read": (args: { conversation: string, message_id: string, }) => rpc.call(methods.mark_read, args),
"prepare_mark_read": (args: { conversation: string, message_id: string, }) => rpc.prepare(methods.mark_read, args),
"events": (args: { after: string, wait_ms: number, }) => rpc.call(methods.events, args)
}; }
