[package]
name = "gchat-api"
description = "Instance-bound gchat UI contract and IPC client"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
publish.workspace = true

[features]
default = ["native"]
native = ["gcoms/ipc", "dep:gcoms-sdk", "dep:tokio", "gcoms-rpc/file-store", "dep:tempfile"]
wasm = ["gcoms/wasm", "gcoms-rpc/wasm"]

[dependencies]
gcoms = { version = "0.1.0", default-features = false, features = ["rpc"] }
gcoms-rpc = { version = "0.1.0", default-features = false }
schemars = "1.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ts-rs = { version = "11", features = ["serde-compat", "no-serde-warnings"] }
gcoms-sdk = { version = "0.1.0", optional = true, default-features = false, features = ["ipc"] }
tokio = { optional = true, version = "1", features = ["time", "fs", "io-util", "rt"] }

[[bin]]
name = "gchat-types"
path = "src/types.rs"

[dependencies.tempfile]
version = "3"
optional = true
