#!/usr/bin/env python3
import os,sys
prompt=sys.argv[1].lower()
github='github.com' in prompt
if 'username' in prompt:print('x-access-token' if github else os.environ['FORGEJO_USER'])
elif 'password' in prompt:print(os.environ['GH_TOKEN'] if github else os.environ['FORGEJO_TOKEN'])
else:raise SystemExit('Unrecognized Git credential prompt')
